import { useRef, useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { gsap } from "gsap/dist/gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger"
import Link from 'next/link'
import { normalizeRepeatedSlashes } from 'next/dist/shared/lib/utils';

export default function Home() {
  const section1 = useRef(null);
  const section2 = useRef(null);
  const section3 = useRef(null);
  const section4 = useRef(null);
  const panels = useRef(null)
  const container = useRef(null)
  const box = useRef(null);
  const progress = useRef(null)

  const [scroll, setScroll] = useState(0);

  useEffect(() => {

      let progressBarHandler = () => {
          
          const totalScroll = document.documentElement.scrollTop;
          const windowHeight = document.documentElement.scrollHeight - document.documentElement.clientHeight;
          const scroll = `${totalScroll / windowHeight}`;

          setScroll(scroll);
      }

      window.addEventListener("scroll", progressBarHandler);

      return () => window.removeEventListener("scroll", progressBarHandler);
  });

  useEffect(() => {
    
    if (typeof window !== "undefined") {
      console.log('hest')
      gsap.registerPlugin(ScrollTrigger); 
    }
    console.log('init gsap')
    let allPanels = gsap.utils.toArray(panels.current.querySelectorAll('.panel'));
    console.log(allPanels, 'sectionssectionssectionssections')

    const sectionsRefs = [section1.current, section2.current, section3.current]
    console.log(sectionsRefs, 'refssss')

    gsap.to(allPanels, {
      yPercent: -100 * (allPanels.length - 1),
      ease: "none",
      scrollTrigger: {
        trigger: section2.current,
        pin: true,
        scrub: 1,
        snap: 1 / (allPanels.length - 1),
        toggleActions: 'play none reverse none',
        // base vertical scrolling on how wide the container is so it feels more natural.
        end: "+=500",
        onUpdate: (self) => console.log('update'),
      }
    });

    gsap.to(box.current, {
      x: 400,
      rotate: 360,
      duration: 3,
      scrollTrigger: {
        trigger: section3.current,
        start: 'top 30%',
        end: "+=100",
        toggleActions: 'play none none reverse',
      }
    })

    gsap.to(section4.current, {
      rotate: 360,
      duration: 3,
      scrollTrigger: {
        trigger: section4.current,
        start: 'top 10%',
        end: "+=100",
        toggleActions: 'play none none reverse',
      }
    })

    sectionsRefs.forEach(section => {
      console.log(section, '*SECTION')
      gsap.from(section.querySelectorAll("h1, p"), {
        scrollTrigger: section.current,
        autoAlpha: 0,
        y: 25,
        duration: 0.75,
        stagger: 0.25
      });
    });

    const body = document.getElementsByTagName('body')

    console.log(document.body.offsetHeight, 'document.body.offsetHeight')
    
    return () => {
    }
  }, [])

  return (
    <div className={styles.container} ref={container}>
      <Head>
        <title>Scroll trigger tester</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="progressBarContainer">
        {/* <div id="progressBar" style={{transform: `scale(${scroll}, 1)`, opacity: `${scroll}`}} /> */}
        <div id="progressBar" style={{transform: `scale(${scroll}, 1)`}} />
      </div>
      <main className={styles.container} >
        
        <div className={`${styles.section} ${styles.section__1}`} ref={section1}>
          <h1>Section 1</h1>
          <div className={`${styles.box} ${styles.box__1}`}></div>
        </div>

        <div className={`${styles.section} ${styles.section__2}`} ref={section2}>
          <div ref={panels} className={styles.panels}>
            <div className="panel">
              <img src="https://picsum.photos/200/300" alt=""/>
              <h1>Some heading</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </div>
            <div className="panel">
              <img src="https://picsum.photos/200/300" alt=""/>
              <h1>Some heading</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </div>
            <div className="panel">
              <img src="https://picsum.photos/200/300" alt=""/>
              <h1>Some heading</h1>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
              </p>
            </div>
          </div>
          <div>
            <img src="https://picsum.photos/600/600" alt=""/>
          </div>
        </div>

        <div className={`${styles.section} ${styles.section__3}`} ref={section3}>
          <h1>Section 3</h1>
          <div className={`${styles.box} ${styles.box__3}`} ref={box}></div>
        </div>

        <div className={`${styles.section}`} ref={section4}>
          <h1>Section 4</h1>
          <div className={`${styles.box} ${styles.box__1}`} ></div>
          <Link href="/about"><h2>About page</h2></Link>
        </div>
      </main>
    </div>
  )
}
